name: Validate file size
on:
  push:
    branches:
      - main

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          minimumsize=4
          for filename in artifacts/*.txt; do
            actualsize=$(du -k "$filename" | cut -f 1)
            echo actual size is $actualsize
            if [ $actualsize -gt $minimumsize ]; then
              echo size of $filename over $minimumsize Kbytes
              exit 1
            else
              echo size is under $minimumsize Kbytes
            fi
          done



