name: Validate file size
on:
  pull_request:

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          minimumsize=10
          for filename in $GITHUB_WORKSPACE/artifacts/*.txt; do
            actualsize=$(du -k "$filename" | cut -f 1)
            if [ $actualsize -gt $minimumsize ]; then
              echo Artifact file size exceeded: $filename
              echo Current $filename size: $actualsize
              echo Mamimum artifact size: $maximumsize
              exit 1
            else
              echo Artifact file size exceeded: $filename
              echo Artifact size: $actualsize
              echo Mamimum artifact size: $maximumsize
              exit 1
            fi
          done



