name: Validate file size
on:
  pull_request:

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          touch $GITHUB_WORKSPACE/artifacts/test.txt
          echo "dslfjalsdjflasjdfljasdlfjlsdjflaksjdf;lajdslf;jsa;fjd;aljsafljdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd" > test.txt
          echo "writed to file "

          minimumsize=1
          for filename in $GITHUB_WORKSPACE/artifacts/*.txt; do
            actualsize=$(du -k "$filename" | cut -f 1)
            if [ $actualsize -ge $minimumsize ]; then
              echo Artifact file size exceeded: $filename;
              echo Current $filename size: $actualsize;
              echo Mamimum artifact size: $maximumsize;
              exit 1
            else
              echo size is under $minimumsize Kbytes
            fi
          done



