name: Validate file size
on:
  push:
    branches:
      - main

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          minimumsize=10
          for filename in artifacts/*.wasm; do
            actualsize=$(wc -c <"$filename")
            if [ $actualsize -ge $minimumsize ]; then
              echo size if over $minimumsize bytes
            else
              echo size is under $minimumsize bytes
            fi
          done


