name: Validate file size
on:
  push:

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          if [ -n "$(find artifacts/ -prune -size +1000000)"]; then
            printf '%s is larger than 1Mb'
          else
            printf '%s is less than 1MB'
          fi
