name: Validate file size
on:
  push:
    branches:
      - main

jobs:
  validate-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file size
        run: |
          minimumsize=1
          for filename in artifacts/*.txt; do
            actualsize=$(du -k "$filename" | cut -f 1)
            if [ $actualsize -ge $minimumsize ]; then
              echo size if over $minimumsize bytes
            else
              echo size is under $minimumsize bytes
            fi
          done


